name: build

on:
  workflow_dispatch:
  push:
    branches:
      - custom-6.7.3

permissions: {}

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Build ReShade (64-bit)
        run: |
          msbuild ReShade.sln /p:Configuration=Release /p:Platform=64-bit /p:RESHADE_ADDON=2 /p:PlatformToolset=v143

      - name: Prepare Output Package
        run: |
          mkdir .\release_package
          
          copy ReShade.ini .\release_package\ReShade.ini
          
          cd .\bin\x64\Release\
          copy ReShade64.dll "..\..\..\release_package\dxgi.dll"
          copy ReShade64.dll "..\..\..\release_package\d3d11.dll"
          copy ReShade64.dll "..\..\..\release_package\d3d12.dll"
          copy ReShade64.dll "..\..\..\release_package\d3d9.dll"
          copy ReShade64.dll "..\..\..\release_package\opengl32.dll"
          copy ReShade64.dll "..\..\..\release_package\vulkan-1.dll"

      - name: Upload Clean ReShade Package
        uses: actions/upload-artifact@v7
        with:
          name: ReShade64-Clean-Package
          path: './release_package/*'
